a=int(input('Enter first number: '))
b=int(input('Enter second number: '))

print('the sum of ',a,'and ',b,'is = ',a+b)
print('the subtract of ',a,'and ',b,'is = ',a-b)
print('the multiplication of ',a,'and ',b,'is = ',a*b)
print('the division of ',a,'and ',b,'is = ',a/b)
print('the integer-division of ',a,'and ',b,'is = ',a//b)
print('the mod of ',a,'and ',b,'is = ',a%b)
print('the square of ',a,'and ',b,'is = ',a**b)